### ISSUE TITLE
fatal: print to "standard output" failed (Broken pipe)

### ISSUE THREAD

**Issue by taymourheikal** [kinnejeff/read-split-fly#5]
Hi @aamcguy @kinnejeff ,

Unfortunately, I'm still getting the same error as I had with RSR. I'm attaching the stderror file (.txt).

Additionally, some scripts start with (e.g. cleanup.sh):
`BASEDIR=$(dirname $(realpath $0))
`
Is it safe to change those to (e.g. rsf_batch_job.sh):
`
BASEDIR=$( cd ${0%/*} >& /dev/null ; pwd -P ) #moved to this method to avoid platform-specific comamnds
`

Hope you guys can help out!

T
[rsf-run1.o9256793.txt](https://github.com/kinnejeff/read-split-fly/files/627943/rsf-run1.o9256793.txt)

**Comment by kinnejeff** [comment]
I'll let Aaron keep looking into it since he started helping.

You asked if we have a manuscript for RSF.  We do, it will be at this 
year's ICIBM and in BMC Bioinformatics.

Yongsheng - Do you mind if we sent the manuscript?  if so, taymourheikal 
please write to us directly from your email so we can send you the 
manuscript directly.  I am jkinne@cs.indstate.edu

-- Jeff

**Comment by aaronmcox** [comment]
T,

I think you may be on to something--it does looks like your system doesn't have realpath.  Definitely changing the code as you suggested will help with this, since BASEDIR only stops working for you once the second version is called (as you noticed).  

Either making that change or installing realpath is probably the fastest way to get you going.  I think this issue was noticed in the past and solved halfway.

As a general note,

The BASEDIR is something that I hadn't made time to look more closely yet, and it probably shouldn't even be in any of of the files but [config.sh](https://github.com/kinnejeff/read-split-fly/blob/master/config.sh).

There may be a file or 2 we haven't sourced the config file.  I'll look into this.

Aaron

**Comment by taymourheikal** [comment]
Hey Aaron,

I fixed all the scripts with realpath, but I'm still getting the same errors pretty much. After the `fatal: print to "standard output" failed (Broken pipe)` error, I'm seeing a `basename: missing operand` (which is also in the .txt file I attached above). I think it's related to line 139 of pipeline.sh: `rsfbase=$(basename $results)`.

Hope this helps.
T

EDIT:
Actually, before it gets there, it hits one of these in bowtie.sh:
```
line 62 outname=$(basename "$(echo $pair1 | cut -d, -f1)")
line 67 outname=$(basename "$(echo $3 | cut -d, -f1)")
```
EDIT2:
I might be wrong about the above; it could be that whatever is causing `fatal: print to "standard output" failed (Broken pipe)` error is compounding and is messing up the basenames.

**Comment by kinnejeff** [comment]
basename is another command that was on the system of the person who did 
that part of RSR, that we later removed (I think) for RSF because it 
wasn't always present.

You said you tried RSF, and there was an error?

I asked the co-authors if they mind publicizing the manuscript for RSF, 
and they said they aren't ready yet.  The quick answer is that memory 
use was improved, parameters were set to optimize for speed, sensitivity 
was improved, the sequences are part of the output, and bugs were fixed.

Note also that you can run small files (a few GB) via a web interface -
   http://bioinf1.indstate.edu/RSR
   http://bioinf1.indstate.edu/RSF

-- Jeff

**Comment by aaronmcox** [comment]
Thanks for following up @taymourheikal.

Tomorrow I'll have some time to work out some of these issues.  I think getting out the GNU-specific commands will be a good start, and I'll also look more closely at the specific files causing problems.  I'll comment here again when I've made some progress.

Aaron

**Comment by taymourheikal** [comment]
Hey @kinnejeff ,
Not a problem- I'll refer to the RSR paper I mentioned earlier, and I'll try to figure out what changes were made through the code. And yea, RSF produces the stderror (.txt) file that I attached at the top of this thread.

@aamcguy ,
Please let me know if I can be of any assistance (testing and running). You can email directly at tah340@nyu.edu . I'm available all day and tomorrow. Much appreciated,
T

**Comment by aaronmcox** [comment]
@taymourheikal ,

I've got all instances of basename, dirname, and realpath out of the code in the [flex branch](https://github.com/kinnejeff/read-split-fly/tree/flex). 

One issue that may or may not be relevant--I'm not sure if you noticed this or not, but we handle the bowtie indexes directory a little bit differently in RSF.  Instead of relying on you to set the BOWTIE_INDEXES environment variable ahead of time, we now explicitly set it in the User Configuration section in [config.sh](https://github.com/kinnejeff/read-split-fly/blob/flex/config.sh).

If you've still got some time, give the version in the flex branch a shot on your data and let me know. 

P.S. If you need a small-ish sample that we sometimes use for testing, we have links to a couple of mm9 data files and bowtie & refflat files [here](http://bioinf1.indstate.edu:3095/about). The following line (with random sample filenames) would provide a reasonably fast run-through of the data without the BLAST queries:

    rsf_batch_job.sh analytic mm9 "mousedata.fastq" 11 13 3 30000 5 2 ~/mm9_example/results_dir 0

**Comment by taymourheikal** [comment]
Success! 👍 
Thanks a lot guys. I really appreciate your responsiveness in this matter.
I also made sure not to export BOWTIE_INDEXES, but set it up in config.sh. I think that may have been causing an issue with the set_indexes() function in bowtie.sh (is BOWTIE_INDEXES_ROOT necessary?).
Thanks again,
T

**Comment by aaronmcox** [comment]
No problem, and thanks for bringing this to our attention. Always good to get input from somebody with fresh eyes.

\- Aaron
